In [1]:
df = [["Milk", "Cake", "Bread", "Eggs", "Tea", "Sugar"],
      ["Knife", "Cake", "Bread", "Eggs", "Tea", "Sugar"],
      ["Milk", "Biscuits", "Eggs", "Tea"],
      ["Milk", "Salt", "Coco", "Eggs", "Sugar"],
      ["Salt", "Cake", "Bread", "Eggs", "Cream", "Sugar"]
     ]

In [2]:
df

[['Milk', 'Cake', 'Bread', 'Eggs', 'Tea', 'Sugar'],
 ['Knife', 'Cake', 'Bread', 'Eggs', 'Tea', 'Sugar'],
 ['Milk', 'Biscuits', 'Eggs', 'Tea'],
 ['Milk', 'Salt', 'Coco', 'Eggs', 'Sugar'],
 ['Salt', 'Cake', 'Bread', 'Eggs', 'Cream', 'Sugar']]

In [3]:
type(df)

list

In [4]:
from mlxtend.preprocessing import TransactionEncoder

In [5]:
te = TransactionEncoder()

In [7]:
te_array = te.fit_transform(df)

In [9]:
te_array

array([[False,  True,  True, False, False,  True, False,  True, False,
         True,  True],
       [False,  True,  True, False, False,  True,  True, False, False,
         True,  True],
       [ True, False, False, False, False,  True, False,  True, False,
        False,  True],
       [False, False, False,  True, False,  True, False,  True,  True,
         True, False],
       [False,  True,  True, False,  True,  True, False, False,  True,
         True, False]])

In [8]:
te.columns_

['Biscuits',
 'Bread',
 'Cake',
 'Coco',
 'Cream',
 'Eggs',
 'Knife',
 'Milk',
 'Salt',
 'Sugar',
 'Tea']

In [10]:
import pandas as pd

In [11]:
df = pd.DataFrame(te_array, columns=te.columns_)

In [12]:
df

   Biscuits  Bread   Cake   Coco  Cream  ...  Knife   Milk   Salt  Sugar    Tea
0     False   True   True  False  False  ...  False   True  False   True   True
1     False   True   True  False  False  ...   True  False  False   True   True
2      True  False  False  False  False  ...  False   True  False  False   True
3     False  False  False   True  False  ...  False   True   True   True  False
4     False   True   True  False   True  ...  False  False   True   True  False

[5 rows x 11 columns]

In [13]:
from mlxtend.frequent_patterns import apriori

In [14]:
freq_itemsets = apriori(df, use_colnames=True)

In [15]:
freq_itemsets

    support                    itemsets
0       0.6                     (Bread)
1       0.6                      (Cake)
2       1.0                      (Eggs)
3       0.6                      (Milk)
4       0.8                     (Sugar)
5       0.6                       (Tea)
6       0.6               (Cake, Bread)
7       0.6               (Eggs, Bread)
8       0.6              (Sugar, Bread)
9       0.6                (Eggs, Cake)
10      0.6               (Sugar, Cake)
11      0.6                (Eggs, Milk)
12      0.8               (Eggs, Sugar)
13      0.6                 (Tea, Eggs)
14      0.6         (Cake, Eggs, Bread)
15      0.6        (Cake, Sugar, Bread)
16      0.6        (Sugar, Eggs, Bread)
17      0.6         (Eggs, Sugar, Cake)
18      0.6  (Sugar, Cake, Eggs, Bread)

In [16]:
from mlxtend.frequent_patterns import association_rules

In [17]:
rules = association_rules(freq_itemsets)

In [18]:
rules

             antecedents           consequents  ...  leverage  conviction
0                 (Cake)               (Bread)  ...      0.24         inf
1                (Bread)                (Cake)  ...      0.24         inf
2                (Bread)                (Eggs)  ...      0.00         inf
3                (Bread)               (Sugar)  ...      0.12         inf
4                 (Cake)                (Eggs)  ...      0.00         inf
5                 (Cake)               (Sugar)  ...      0.12         inf
6                 (Milk)                (Eggs)  ...      0.00         inf
7                 (Eggs)               (Sugar)  ...      0.00         1.0
8                (Sugar)                (Eggs)  ...      0.00         inf
9                  (Tea)                (Eggs)  ...      0.00         inf
10          (Eggs, Cake)               (Bread)  ...      0.24         inf
11         (Bread, Cake)                (Eggs)  ...      0.00         inf
12         (Eggs, Bread)                (Cake)  ...      0.24         inf
13                (Cake)         (Eggs, Bread)  ...      0.24         inf
14               (Bread)          (Eggs, Cake)  ...      0.24         inf
15         (Sugar, Cake)               (Bread)  ...      0.24         inf
16         (Bread, Cake)               (Sugar)  ...      0.12         inf
17        (Sugar, Bread)                (Cake)  ...      0.24         inf
18                (Cake)        (Sugar, Bread)  ...      0.24         inf
19               (Bread)         (Sugar, Cake)  ...      0.24         inf
20        (Sugar, Bread)                (Eggs)  ...      0.00         inf
21         (Eggs, Bread)               (Sugar)  ...      0.12         inf
22               (Bread)         (Eggs, Sugar)  ...      0.12         inf
23          (Eggs, Cake)               (Sugar)  ...      0.12         inf
24         (Sugar, Cake)                (Eggs)  ...      0.00         inf
25                (Cake)         (Sugar, Eggs)  ...      0.12         inf
26   (Eggs, Sugar, Cake)               (Bread)  ...      0.24         inf
27  (Sugar, Bread, Cake)                (Eggs)  ...      0.00         inf
28  (Eggs, Sugar, Bread)                (Cake)  ...      0.24         inf
29   (Eggs, Bread, Cake)               (Sugar)  ...      0.12         inf
30         (Sugar, Cake)         (Eggs, Bread)  ...      0.24         inf
31        (Sugar, Bread)          (Eggs, Cake)  ...      0.24         inf
32          (Eggs, Cake)        (Sugar, Bread)  ...      0.24         inf
33         (Bread, Cake)         (Eggs, Sugar)  ...      0.12         inf
34         (Eggs, Bread)         (Sugar, Cake)  ...      0.24         inf
35                (Cake)  (Eggs, Sugar, Bread)  ...      0.24         inf
36               (Bread)   (Eggs, Sugar, Cake)  ...      0.24         inf

[37 rows x 9 columns]

In [19]:
rules = rules[["antecedents", "consequents", "support", "confidence"]]

In [20]:
rules

             antecedents           consequents  support  confidence
0                 (Cake)               (Bread)      0.6         1.0
1                (Bread)                (Cake)      0.6         1.0
2                (Bread)                (Eggs)      0.6         1.0
3                (Bread)               (Sugar)      0.6         1.0
4                 (Cake)                (Eggs)      0.6         1.0
5                 (Cake)               (Sugar)      0.6         1.0
6                 (Milk)                (Eggs)      0.6         1.0
7                 (Eggs)               (Sugar)      0.8         0.8
8                (Sugar)                (Eggs)      0.8         1.0
9                  (Tea)                (Eggs)      0.6         1.0
10          (Eggs, Cake)               (Bread)      0.6         1.0
11         (Bread, Cake)                (Eggs)      0.6         1.0
12         (Eggs, Bread)                (Cake)      0.6         1.0
13                (Cake)         (Eggs, Bread)      0.6         1.0
14               (Bread)          (Eggs, Cake)      0.6         1.0
15         (Sugar, Cake)               (Bread)      0.6         1.0
16         (Bread, Cake)               (Sugar)      0.6         1.0
17        (Sugar, Bread)                (Cake)      0.6         1.0
18                (Cake)        (Sugar, Bread)      0.6         1.0
19               (Bread)         (Sugar, Cake)      0.6         1.0
20        (Sugar, Bread)                (Eggs)      0.6         1.0
21         (Eggs, Bread)               (Sugar)      0.6         1.0
22               (Bread)         (Eggs, Sugar)      0.6         1.0
23          (Eggs, Cake)               (Sugar)      0.6         1.0
24         (Sugar, Cake)                (Eggs)      0.6         1.0
25                (Cake)         (Sugar, Eggs)      0.6         1.0
26   (Eggs, Sugar, Cake)               (Bread)      0.6         1.0
27  (Sugar, Bread, Cake)                (Eggs)      0.6         1.0
28  (Eggs, Sugar, Bread)                (Cake)      0.6         1.0
29   (Eggs, Bread, Cake)               (Sugar)      0.6         1.0
30         (Sugar, Cake)         (Eggs, Bread)      0.6         1.0
31        (Sugar, Bread)          (Eggs, Cake)      0.6         1.0
32          (Eggs, Cake)        (Sugar, Bread)      0.6         1.0
33         (Bread, Cake)         (Eggs, Sugar)      0.6         1.0
34         (Eggs, Bread)         (Sugar, Cake)      0.6         1.0
35                (Cake)  (Eggs, Sugar, Bread)      0.6         1.0
36               (Bread)   (Eggs, Sugar, Cake)      0.6         1.0